loggin:
  config: classpath:logback-spring.xml
params:
  path: D:/dir
server:
  port: 8080
  #生产注释掉
#  port: 8088
#  servlet:
#    context-path: /bishe
spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/bishe?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    url: jdbc:mysql://192.168.1.5:3306/bishe?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
#    password: Password_bishe132
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.ynet.fullview.model
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
  helper-dialect: mysql

fdfs:
  #IMAGE_SERVER_URL=http://192.168.25.133/
  # 读取时间
  soTimeout: 1500
  # 连接超时时间
  connectTimeout: 1500
  # 编码默认UTF-8，charset属性不能自定义
  #charset: UTF-8
  # 缩略图
  thumbImage:
    # 宽
    width: 150
    # 高
    height: 150
  # tracker列表
  trackerList:
    #- fastDFS的IP:端口39.98.163.208
    39.98.163.208:22122


